"""add localizaciones_interes table

Revision ID: 01167a50721b
Revises: 1065f907c4da
Create Date: 2025-05-04 12:59:09.407908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01167a50721b'
down_revision: Union[str, None] = '1065f907c4da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localizaciones_interes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('id_lectura', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.String(length=30), nullable=False),
    sa.Column('icono', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('coordenada_x', sa.Float(), nullable=False),
    sa.Column('coordenada_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['Casos.ID_Caso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localizaciones_interes_caso_id'), 'localizaciones_interes', ['caso_id'], unique=False)
    op.create_index(op.f('ix_localizaciones_interes_id'), 'localizaciones_interes', ['id'], unique=False)
    op.create_index(op.f('ix_localizaciones_interes_id_lectura'), 'localizaciones_interes', ['id_lectura'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_localizaciones_interes_id_lectura'), table_name='localizaciones_interes')
    op.drop_index(op.f('ix_localizaciones_interes_id'), table_name='localizaciones_interes')
    op.drop_index(op.f('ix_localizaciones_interes_caso_id'), table_name='localizaciones_interes')
    op.drop_table('localizaciones_interes')
    # ### end Alembic commands ###
