"""Add Modelo, Propiedad, Observaciones, Sospechoso to Vehiculo and modify Alquiler

Revision ID: 09ef5264971b
Revises: 
Create Date: 2025-04-14 00:01:45.928994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ef5264971b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('Lectores', schema=None) as batch_op:
    #     batch_op.drop_index('ix_Lectores_ID_Lector')

    # op.drop_table('Lectores')
    # with op.batch_alter_table('Lecturas', schema=None) as batch_op:
    #     batch_op.drop_index('ix_Lecturas_Fecha_y_Hora')
    #     batch_op.drop_index('ix_Lecturas_ID_Lectura')
    #     batch_op.drop_index('ix_Lecturas_Tipo_Fuente')
    #     batch_op.drop_index('ix_lecturas_matricula')

    # op.drop_table('Lecturas')
    # with op.batch_alter_table('LecturasRelevantes', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'lectura', ['ID_Lectura'], ['ID_Lectura'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('LecturasRelevantes', schema=None) as batch_op:
    #     batch_op.drop_constraint(None, type_='foreignkey')
    #     batch_op.create_foreign_key(None, 'Lecturas', ['ID_Lectura'], ['ID_Lectura'])

    op.create_table('Lecturas',
    sa.Column('ID_Lectura', sa.INTEGER(), nullable=False),
    sa.Column('ID_Archivo', sa.INTEGER(), nullable=False),
    sa.Column('Matricula', sa.TEXT(), nullable=False),
    sa.Column('Fecha_y_Hora', sa.DATETIME(), nullable=False),
    sa.Column('Carril', sa.TEXT(), nullable=True),
    sa.Column('Velocidad', sa.FLOAT(), nullable=True),
    sa.Column('ID_Lector', sa.VARCHAR(), nullable=True),
    sa.Column('Coordenada_X', sa.FLOAT(), nullable=True),
    sa.Column('Coordenada_Y', sa.FLOAT(), nullable=True),
    sa.Column('Tipo_Fuente', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Archivo'], ['ArchivosExcel.ID_Archivo'], ),
    sa.ForeignKeyConstraint(['ID_Lector'], ['Lectores.ID_Lector'], ),
    sa.PrimaryKeyConstraint('ID_Lectura')
    )
    with op.batch_alter_table('Lecturas', schema=None) as batch_op:
        batch_op.create_index('ix_lecturas_matricula', ['Matricula'], unique=False)
        batch_op.create_index('ix_Lecturas_Tipo_Fuente', ['Tipo_Fuente'], unique=False)
        batch_op.create_index('ix_Lecturas_ID_Lectura', ['ID_Lectura'], unique=False)
        batch_op.create_index('ix_Lecturas_Fecha_y_Hora', ['Fecha_y_Hora'], unique=False)

    op.create_table('Lectores',
    sa.Column('ID_Lector', sa.TEXT(), nullable=False),
    sa.Column('Coordenada_X', sa.FLOAT(), nullable=False),
    sa.Column('Coordenada_Y', sa.FLOAT(), nullable=False),
    sa.Column('Sentido_de_la_Marcha', sa.TEXT(), nullable=True),
    sa.Column('Organismo', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('ID_Lector')
    )
    with op.batch_alter_table('Lectores', schema=None) as batch_op:
        batch_op.create_index('ix_Lectores_ID_Lector', ['ID_Lector'], unique=False)

    # ### end Alembic commands ###
