"""initial schema with usuarios

Revision ID: efd3af6359bc
Revises: 
Create Date: 2025-05-09 19:40:11.135839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd3af6359bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grupos',
    sa.Column('ID_Grupo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=False),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.Column('Fecha_Creacion', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Grupo')
    )
    op.create_index(op.f('ix_Grupos_ID_Grupo'), 'Grupos', ['ID_Grupo'], unique=False)
    op.create_index(op.f('ix_Grupos_Nombre'), 'Grupos', ['Nombre'], unique=True)
    op.create_table('Vehiculos',
    sa.Column('ID_Vehiculo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Matricula', sa.Text(), nullable=False),
    sa.Column('Marca', sa.Text(), nullable=True),
    sa.Column('Modelo', sa.Text(), nullable=True),
    sa.Column('Color', sa.Text(), nullable=True),
    sa.Column('Propiedad', sa.Text(), nullable=True),
    sa.Column('Alquiler', sa.Boolean(), nullable=False),
    sa.Column('Observaciones', sa.Text(), nullable=True),
    sa.Column('Comprobado', sa.Boolean(), nullable=False),
    sa.Column('Sospechoso', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Vehiculo')
    )
    op.create_index(op.f('ix_Vehiculos_ID_Vehiculo'), 'Vehiculos', ['ID_Vehiculo'], unique=False)
    op.create_index(op.f('ix_Vehiculos_Matricula'), 'Vehiculos', ['Matricula'], unique=True)
    op.create_table('lector',
    sa.Column('ID_Lector', sa.String(length=50), nullable=False),
    sa.Column('Nombre', sa.String(length=100), nullable=True),
    sa.Column('Carretera', sa.String(length=100), nullable=True),
    sa.Column('Provincia', sa.String(length=50), nullable=True),
    sa.Column('Localidad', sa.String(length=100), nullable=True),
    sa.Column('Sentido', sa.String(length=50), nullable=True),
    sa.Column('Orientacion', sa.String(length=100), nullable=True),
    sa.Column('Organismo_Regulador', sa.String(length=100), nullable=True),
    sa.Column('Contacto', sa.String(length=255), nullable=True),
    sa.Column('Coordenada_X', sa.Float(), nullable=True),
    sa.Column('Coordenada_Y', sa.Float(), nullable=True),
    sa.Column('Texto_Libre', sa.Text(), nullable=True),
    sa.Column('Imagen_Path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ID_Lector')
    )
    op.create_index(op.f('ix_lector_ID_Lector'), 'lector', ['ID_Lector'], unique=False)
    op.create_index(op.f('ix_lector_Organismo_Regulador'), 'lector', ['Organismo_Regulador'], unique=False)
    op.create_table('Casos',
    sa.Column('ID_Caso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre_del_Caso', sa.Text(), nullable=False),
    sa.Column('Año', sa.Integer(), nullable=False),
    sa.Column('NIV', sa.String(length=50), nullable=True),
    sa.Column('Descripcion', sa.Text(), nullable=True),
    sa.Column('Fecha_de_Creacion', sa.Date(), nullable=False),
    sa.Column('Estado', sa.String(length=50), nullable=False),
    sa.Column('ID_Grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Grupo'], ['Grupos.ID_Grupo'], ),
    sa.PrimaryKeyConstraint('ID_Caso')
    )
    op.create_index(op.f('ix_Casos_Estado'), 'Casos', ['Estado'], unique=False)
    op.create_index(op.f('ix_Casos_ID_Caso'), 'Casos', ['ID_Caso'], unique=False)
    op.create_index(op.f('ix_Casos_ID_Grupo'), 'Casos', ['ID_Grupo'], unique=False)
    op.create_index(op.f('ix_Casos_Nombre_del_Caso'), 'Casos', ['Nombre_del_Caso'], unique=True)
    op.create_table('usuarios',
    sa.Column('User', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('Contraseña', sa.String(length=128), nullable=False),
    sa.Column('Rol', sa.Enum('superadmin', 'admin_casos', name='rolusuarioenum'), nullable=False),
    sa.Column('ID_Grupo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Grupo'], ['Grupos.ID_Grupo'], ),
    sa.PrimaryKeyConstraint('User')
    )
    op.create_index(op.f('ix_usuarios_User'), 'usuarios', ['User'], unique=True)
    op.create_table('ArchivosExcel',
    sa.Column('ID_Archivo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Caso', sa.Integer(), nullable=False),
    sa.Column('Nombre_del_Archivo', sa.Text(), nullable=False),
    sa.Column('Tipo_de_Archivo', sa.Text(), nullable=False),
    sa.Column('Fecha_de_Importacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Caso'], ['Casos.ID_Caso'], ),
    sa.PrimaryKeyConstraint('ID_Archivo')
    )
    op.create_index(op.f('ix_ArchivosExcel_ID_Archivo'), 'ArchivosExcel', ['ID_Archivo'], unique=False)
    op.create_table('gps_capas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('lecturas', sa.JSON(), nullable=False),
    sa.Column('filtros', sa.JSON(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['Casos.ID_Caso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gps_capas_id'), 'gps_capas', ['id'], unique=False)
    op.create_table('localizaciones_interes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('id_lectura', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_hora', sa.String(length=30), nullable=False),
    sa.Column('icono', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('coordenada_x', sa.Float(), nullable=False),
    sa.Column('coordenada_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['Casos.ID_Caso'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_localizaciones_interes_caso_id'), 'localizaciones_interes', ['caso_id'], unique=False)
    op.create_index(op.f('ix_localizaciones_interes_id'), 'localizaciones_interes', ['id'], unique=False)
    op.create_index(op.f('ix_localizaciones_interes_id_lectura'), 'localizaciones_interes', ['id_lectura'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['Casos.ID_Caso'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_caso_id'), 'saved_searches', ['caso_id'], unique=False)
    op.create_index(op.f('ix_saved_searches_id'), 'saved_searches', ['id'], unique=False)
    op.create_table('lectura',
    sa.Column('ID_Lectura', sa.Integer(), nullable=False),
    sa.Column('ID_Archivo', sa.Integer(), nullable=False),
    sa.Column('Matricula', sa.String(length=20), nullable=False),
    sa.Column('Fecha_y_Hora', sa.DateTime(), nullable=False),
    sa.Column('Carril', sa.String(length=50), nullable=True),
    sa.Column('Velocidad', sa.Float(), nullable=True),
    sa.Column('ID_Lector', sa.String(length=50), nullable=True),
    sa.Column('Coordenada_X', sa.Float(), nullable=True),
    sa.Column('Coordenada_Y', sa.Float(), nullable=True),
    sa.Column('Tipo_Fuente', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['ID_Archivo'], ['ArchivosExcel.ID_Archivo'], ),
    sa.ForeignKeyConstraint(['ID_Lector'], ['lector.ID_Lector'], ),
    sa.PrimaryKeyConstraint('ID_Lectura')
    )
    op.create_index(op.f('ix_lectura_Fecha_y_Hora'), 'lectura', ['Fecha_y_Hora'], unique=False)
    op.create_index(op.f('ix_lectura_ID_Lector'), 'lectura', ['ID_Lector'], unique=False)
    op.create_index(op.f('ix_lectura_ID_Lectura'), 'lectura', ['ID_Lectura'], unique=False)
    op.create_index(op.f('ix_lectura_Matricula'), 'lectura', ['Matricula'], unique=False)
    op.create_table('LecturasRelevantes',
    sa.Column('ID_Relevante', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Lectura', sa.Integer(), nullable=False),
    sa.Column('Fecha_Marcada', sa.DateTime(), nullable=False),
    sa.Column('Nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Lectura'], ['lectura.ID_Lectura'], ),
    sa.PrimaryKeyConstraint('ID_Relevante'),
    sa.UniqueConstraint('ID_Lectura')
    )
    op.create_index(op.f('ix_LecturasRelevantes_ID_Relevante'), 'LecturasRelevantes', ['ID_Relevante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_LecturasRelevantes_ID_Relevante'), table_name='LecturasRelevantes')
    op.drop_table('LecturasRelevantes')
    op.drop_index(op.f('ix_lectura_Matricula'), table_name='lectura')
    op.drop_index(op.f('ix_lectura_ID_Lectura'), table_name='lectura')
    op.drop_index(op.f('ix_lectura_ID_Lector'), table_name='lectura')
    op.drop_index(op.f('ix_lectura_Fecha_y_Hora'), table_name='lectura')
    op.drop_table('lectura')
    op.drop_index(op.f('ix_saved_searches_id'), table_name='saved_searches')
    op.drop_index(op.f('ix_saved_searches_caso_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_localizaciones_interes_id_lectura'), table_name='localizaciones_interes')
    op.drop_index(op.f('ix_localizaciones_interes_id'), table_name='localizaciones_interes')
    op.drop_index(op.f('ix_localizaciones_interes_caso_id'), table_name='localizaciones_interes')
    op.drop_table('localizaciones_interes')
    op.drop_index(op.f('ix_gps_capas_id'), table_name='gps_capas')
    op.drop_table('gps_capas')
    op.drop_index(op.f('ix_ArchivosExcel_ID_Archivo'), table_name='ArchivosExcel')
    op.drop_table('ArchivosExcel')
    op.drop_index(op.f('ix_usuarios_User'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_Casos_Nombre_del_Caso'), table_name='Casos')
    op.drop_index(op.f('ix_Casos_ID_Grupo'), table_name='Casos')
    op.drop_index(op.f('ix_Casos_ID_Caso'), table_name='Casos')
    op.drop_index(op.f('ix_Casos_Estado'), table_name='Casos')
    op.drop_table('Casos')
    op.drop_index(op.f('ix_lector_Organismo_Regulador'), table_name='lector')
    op.drop_index(op.f('ix_lector_ID_Lector'), table_name='lector')
    op.drop_table('lector')
    op.drop_index(op.f('ix_Vehiculos_Matricula'), table_name='Vehiculos')
    op.drop_index(op.f('ix_Vehiculos_ID_Vehiculo'), table_name='Vehiculos')
    op.drop_table('Vehiculos')
    op.drop_index(op.f('ix_Grupos_Nombre'), table_name='Grupos')
    op.drop_index(op.f('ix_Grupos_ID_Grupo'), table_name='Grupos')
    op.drop_table('Grupos')
    # ### end Alembic commands ###
